version: "3"

services:
  build:
    container_name: "build"
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - exports:/app/exports

volumes:
  exports:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./exports
