version: "3"

services:
  train:
    container_name: "train"
    build:
      context: .
      dockerfile: train.Dockerfile
    volumes:
      - exports:/app/exports
  server:
    container_name: "server"
    build:
      context: .
      dockerfile: server.Dockerfile
    volumes:
      - exports:/app/imports
    ports:
      - "80:8080"
    depends_on:
      train:
        condition: service_completed_successfully

volumes:
  exports:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./exports
